# Site settings
title: Mitul Mistry - Tech Blog
email: MitulMistryDev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mitul Mistry, full-stack developer and designer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mitulmistry.github.io/" # the base hostname & protocol for your site
twitter_username: mmystic
github_username:  MitulMistry

# Build settings
markdown: kramdown